apiVersion: v1
kind: Secret
metadata:
  name: quantis-secrets
type: Opaque
data:
  database-url: bXlzcWw6Ly9hcHB1c2VyOmRldi1wYXNzd29yZEBhcHAtZGF0YWJhc2U6MzMwNi9hcHBkYg==
  jwt-secret: ZGV2LWp3dC1zZWNyZXQ=
  mysql-root-password: ZGV2LXJvb3QtcGFzc3dvcmQ=
  mysql-password: ZGV2LXBhc3N3b3Jk
  api-key: ZGV2LWFwaS1rZXk=
